In [41]:
import mysql.connector

### Connecting to Database of SQL:

In [72]:
conn = mysql.connector.connect(
    host = "localhost",
    user = "root",
    password = "mysql",
    database = "hospital_management_system"
)
cursor = conn.cursor()

#### Showing All the Tables in the hospital_management_system:

In [115]:
cursor.execute("show tables")
Table_name = cursor.fetchall()
for i in Table_name:
    for a in i:
        print(a)    ## where a is a random alphabet iterator that shows the particular table name.

appointments
billing
doctors
medicalrecords
patients

#### Patients Table Description :

In [177]:
cursor.execute("desc patients")
Column_name = cursor.fetchall()
for i in Column_name:
    print(i)

('patient_id', 'int', 'NO', 'PRI', None, 'auto_increment')
('patient_name', 'varchar(60)', 'YES', '', None, '')
('age', 'int', 'NO', '', None, '')
('gender', "enum('Male','Female')", 'NO', '', None, '')
('address', 'varchar(255)', 'YES', '', None, '')
('contact_number', 'varchar(15)', 'NO', 'UNI', None, '')
('medical_history', 'text', 'YES', '', None, '')

### Retrieving Data of Patients Table:

In [223]:
cursor.execute("SELECT * FROM patients")
patients = cursor.fetchall()
print("Patient Records:")
for patient in patients:
    print(f"ID: {patient[0]}, Name: {patient[1]}, Age: {patient[2]}, Gender: {patient[3]}, Disease: {patient[4]}")

Patient Records:
ID: 1, Name: Neha Verma 1, Age: 89, Gender: Male, Disease: Chennai
ID: 2, Name: Ramesh Iyer 2, Age: 52, Gender: Male, Disease: Jaipur
ID: 3, Name: Deepika Reddy 3, Age: 82, Gender: Female, Disease: Hyderabad
ID: 4, Name: Priya Kapoor 4, Age: 77, Gender: Male, Disease: Chennai
ID: 5, Name: Rahul Sharma 5, Age: 37, Gender: Male, Disease: Jaipur
ID: 6, Name: Pooja Thakur 6, Age: 77, Gender: Female, Disease: Pune
ID: 7, Name: Priya Kapoor 7, Age: 12, Gender: Female, Disease: Jaipur
ID: 8, Name: Ramesh Iyer 8, Age: 86, Gender: Male, Disease: Jaipur
ID: 9, Name: Neha Verma 9, Age: 2, Gender: Female, Disease: Kolkata
ID: 10, Name: Alok Singh 10, Age: 72, Gender: Female, Disease: Mumbai
ID: 11, Name: Suresh Patil 11, Age: 58, Gender: Male, Disease: Bangalore
ID: 12, Name: Neha Verma 12, Age: 87, Gender: Male, Disease: Jaipur
ID: 13, Name: Deepika Reddy 13, Age: 5, Gender: Male, Disease: Delhi
ID: 14, Name: Rahul Sharma 14, Age: 58, Gender: Male, Disease: Delhi
ID: 15, Name: Vikas Mehta 15, Age: 50, Gender: Male, Disease: Mumbai
ID: 16, Name: Amit Khanna 16, Age: 65, Gender: Female, Disease: Pune
ID: 17, Name: Pooja Thakur 17, Age: 9, Gender: Male, Disease: Bangalore
ID: 18, Name: Neha Verma 18, Age: 43, Gender: Male, Disease: Bangalore
ID: 19, Name: Ramesh Iyer 19, Age: 39, Gender: Female, Disease: Bangalore
ID: 20, Name: Amit Khanna 20, Age: 40, Gender: Female, Disease: Chennai
ID: 21, Name: Ramesh Iyer 21, Age: 2, Gender: Male, Disease: Mumbai
ID: 22, Name: Vikas Mehta 22, Age: 88, Gender: Female, Disease: Chennai
ID: 23, Name: Amit Khanna 23, Age: 40, Gender: Male, Disease: Kolkata
ID: 24, Name: Manish Gupta 24, Age: 66, Gender: Female, Disease: Bangalore
ID: 25, Name: Pooja Thakur 25, Age: 31, Gender: Male, Disease: Delhi
ID: 26, Name: Neha Verma 26, Age: 14, Gender: Male, Disease: Ahmedabad
ID: 27, Name: Amit Khanna 27, Age: 38, Gender: Male, Disease: Pune
ID: 28, Name: Neha Verma 28, Age: 33, Gender: Female, Disease: Jaipur
ID: 29, Name: Amit Khanna 29, Age: 84, Gender: Male, Disease: Mumbai
ID: 30, Name: Priya Kapoor 30, Age: 89, Gender: Male, Disease: Pune
ID: 31, Name: Vikas Mehta 31, Age: 13, Gender: Male, Disease: Ahmedabad
ID: 32, Name: Priya Kapoor 32, Age: 43, Gender: Male, Disease: Bangalore
ID: 33, Name: Deepika Reddy 33, Age: 66, Gender: Male, Disease: Jaipur
ID: 34, Name: Manish Gupta 34, Age: 35, Gender: Male, Disease: Pune
ID: 35, Name: Pooja Thakur 35, Age: 31, Gender: Male, Disease: Hyderabad
ID: 36, Name: Priya Kapoor 36, Age: 7, Gender: Female, Disease: Mumbai
ID: 37, Name: Deepika Reddy 37, Age: 75, Gender: Female, Disease: Bangalore
ID: 38, Name: Rahul Sharma 38, Age: 65, Gender: Female, Disease: Bangalore
ID: 39, Name: Priya Kapoor 39, Age: 32, Gender: Male, Disease: Ahmedabad
ID: 40, Name: Pooja Thakur 40, Age: 36, Gender: Female, Disease: Hyderabad
ID: 41, Name: Suresh Patil 41, Age: 85, Gender: Female, Disease: Chennai
ID: 42, Name: Priya Kapoor 42, Age: 89, Gender: Male, Disease: Kolkata
ID: 43, Name: Priya Kapoor 43, Age: 41, Gender: Male, Disease: Jaipur
ID: 44, Name: Manish Gupta 44, Age: 78, Gender: Female, Disease: Pune
ID: 45, Name: Neha Verma 45, Age: 63, Gender: Male, Disease: Delhi
ID: 46, Name: Priya Kapoor 46, Age: 64, Gender: Female, Disease: Pune
ID: 47, Name: Suresh Patil 47, Age: 15, Gender: Male, Disease: Jaipur
ID: 48, Name: Deepika Reddy 48, Age: 69, Gender: Male, Disease: Jaipur
ID: 49, Name: Deepika Reddy 49, Age: 79, Gender: Male, Disease: Kolkata
ID: 50, Name: Deepika Reddy 50, Age: 30, Gender: Male, Disease: Hyderabad
ID: 51, Name: Pooja Thakur 51, Age: 49, Gender: Female, Disease: Kolkata
ID: 52, Name: Anjali Rao 52, Age: 78, Gender: Male, Disease: Bangalore
ID: 53, Name: Manish Gupta 53, Age: 61, Gender: Male, Disease: Ahmedabad
ID: 54, Name: Vikas Mehta 54, Age: 2, Gender: Female, Disease: Ahmedabad
ID: 55, Name: Anjali Rao 55, Age: 32, Gender: Female, Disease: Chennai
ID: 56, Name: Suresh Patil 56, Age: 51, Gender: Male, Disease: Delhi
ID: 57, Name: Ramesh Iyer 57, Age: 81, Gender: Female, Disease: Ahmedabad
ID: 58, Name: Priya Kapoor 58, Age: 86, Gender: Male, Disease: Ahmedabad
ID: 59, Name: Pooja Thakur 59, Age: 27, Gender: Male, Disease: Delhi
ID: 60, Name: Vikas Mehta 60, Age: 16, Gender: Female, Disease: Bangalore
ID: 61, Name: Suresh Patil 61, Age: 21, Gender: Female, Disease: Ahmedabad
ID: 62, Name: Suresh Patil 62, Age: 56, Gender: Female, Disease: Kolkata
ID: 63, Name: Amit Khanna 63, Age: 23, Gender: Female, Disease: Delhi
ID: 64, Name: Manish Gupta 64, Age: 79, Gender: Male, Disease: Kolkata
ID: 65, Name: Neha Verma 65, Age: 75, Gender: Female, Disease: Pune
ID: 66, Name: Amit Khanna 66, Age: 88, Gender: Female, Disease: Chennai
ID: 67, Name: Pooja Thakur 67, Age: 30, Gender: Female, Disease: Delhi
ID: 68, Name: Ramesh Iyer 68, Age: 10, Gender: Female, Disease: Mumbai
ID: 69, Name: Pooja Thakur 69, Age: 51, Gender: Female, Disease: Ahmedabad
ID: 70, Name: Anjali Rao 70, Age: 88, Gender: Male, Disease: Bangalore
ID: 71, Name: Rahul Sharma 71, Age: 9, Gender: Male, Disease: Delhi
ID: 72, Name: Pooja Thakur 72, Age: 77, Gender: Male, Disease: Jaipur
ID: 73, Name: Rahul Sharma 73, Age: 15, Gender: Male, Disease: Ahmedabad
ID: 74, Name: Priya Kapoor 74, Age: 42, Gender: Male, Disease: Delhi
ID: 75, Name: Vikas Mehta 75, Age: 27, Gender: Male, Disease: Kolkata
ID: 76, Name: Manish Gupta 76, Age: 48, Gender: Male, Disease: Delhi
ID: 77, Name: Manish Gupta 77, Age: 13, Gender: Male, Disease: Hyderabad
ID: 78, Name: Amit Khanna 78, Age: 12, Gender: Female, Disease: Kolkata
ID: 79, Name: Deepika Reddy 79, Age: 5, Gender: Female, Disease: Pune
ID: 80, Name: Suresh Patil 80, Age: 46, Gender: Male, Disease: Pune
ID: 81, Name: Amit Khanna 81, Age: 20, Gender: Female, Disease: Bangalore
ID: 82, Name: Suresh Patil 82, Age: 67, Gender: Male, Disease: Hyderabad
ID: 83, Name: Amit Khanna 83, Age: 75, Gender: Female, Disease: Kolkata
ID: 84, Name: Neha Verma 84, Age: 13, Gender: Female, Disease: Jaipur
ID: 85, Name: Priya Kapoor 85, Age: 71, Gender: Male, Disease: Jaipur
ID: 86, Name: Vikas Mehta 86, Age: 78, Gender: Female, Disease: Chennai
ID: 87, Name: Anjali Rao 87, Age: 9, Gender: Male, Disease: Ahmedabad
ID: 88, Name: Manish Gupta 88, Age: 38, Gender: Male, Disease: Bangalore
ID: 89, Name: Pooja Thakur 89, Age: 36, Gender: Male, Disease: Kolkata
ID: 90, Name: Manish Gupta 90, Age: 76, Gender: Female, Disease: Pune
ID: 91, Name: Neha Verma 91, Age: 60, Gender: Male, Disease: Ahmedabad
ID: 92, Name: Neha Verma 92, Age: 24, Gender: Female, Disease: Jaipur
ID: 93, Name: Deepika Reddy 93, Age: 84, Gender: Female, Disease: Bangalore
ID: 94, Name: Priya Kapoor 94, Age: 30, Gender: Female, Disease: Hyderabad
ID: 95, Name: Ramesh Iyer 95, Age: 28, Gender: Female, Disease: Jaipur
ID: 96, Name: Vikas Mehta 96, Age: 65, Gender: Male, Disease: Ahmedabad
ID: 97, Name: Amit Khanna 97, Age: 74, Gender: Female, Disease: Kolkata
ID: 98, Name: Pooja Thakur 98, Age: 64, Gender: Female, Disease: Mumbai
ID: 99, Name: Anjali Rao 99, Age: 68, Gender: Female, Disease: Ahmedabad
ID: 100, Name: Manish Gupta 100, Age: 43, Gender: Female, Disease: Delhi
ID: 101, Name: Amit Khanna 101, Age: 21, Gender: Male, Disease: Ahmedabad
ID: 102, Name: Suresh Patil 102, Age: 38, Gender: Male, Disease: Pune
ID: 103, Name: Deepika Reddy 103, Age: 82, Gender: Female, Disease: Hyderabad
ID: 104, Name: Priya Kapoor 104, Age: 77, Gender: Male, Disease: Hyderabad
ID: 105, Name: Deepika Reddy 105, Age: 68, Gender: Female, Disease: Hyderabad
ID: 106, Name: Amit Khanna 106, Age: 25, Gender: Female, Disease: Delhi
ID: 107, Name: Rahul Sharma 107, Age: 28, Gender: Male, Disease: Jaipur
ID: 108, Name: Neha Verma 108, Age: 17, Gender: Female, Disease: Pune
ID: 109, Name: Vikas Mehta 109, Age: 63, Gender: Male, Disease: Hyderabad
ID: 110, Name: Manish Gupta 110, Age: 65, Gender: Female, Disease: Mumbai
ID: 111, Name: Ramesh Iyer 111, Age: 12, Gender: Female, Disease: Delhi
ID: 112, Name: Neha Verma 112, Age: 12, Gender: Female, Disease: Kolkata
ID: 113, Name: Suresh Patil 113, Age: 33, Gender: Female, Disease: Ahmedabad
ID: 114, Name: Anjali Rao 114, Age: 46, Gender: Male, Disease: Bangalore
ID: 115, Name: Vikas Mehta 115, Age: 34, Gender: Male, Disease: Pune
ID: 116, Name: Neha Verma 116, Age: 2, Gender: Female, Disease: Kolkata
ID: 117, Name: Anjali Rao 117, Age: 51, Gender: Male, Disease: Hyderabad
ID: 118, Name: Amit Khanna 118, Age: 80, Gender: Female, Disease: Bangalore
ID: 119, Name: Vikas Mehta 119, Age: 72, Gender: Male, Disease: Hyderabad
ID: 120, Name: Rahul Sharma 120, Age: 5, Gender: Female, Disease: Chennai
ID: 121, Name: Rahul Sharma 121, Age: 90, Gender: Male, Disease: Chennai
ID: 122, Name: Priya Kapoor 122, Age: 39, Gender: Male, Disease: Ahmedabad
ID: 123, Name: Anjali Rao 123, Age: 49, Gender: Female, Disease: Hyderabad
ID: 124, Name: Deepika Reddy 124, Age: 39, Gender: Female, Disease: Kolkata
ID: 125, Name: Ramesh Iyer 125, Age: 28, Gender: Male, Disease: Bangalore
ID: 126, Name: Pooja Thakur 126, Age: 63, Gender: Female, Disease: Jaipur
ID: 127, Name: Deepika Reddy 127, Age: 13, Gender: Male, Disease: Bangalore
ID: 128, Name: Alok Singh 128, Age: 46, Gender: Female, Disease: Hyderabad
ID: 129, Name: Rahul Sharma 129, Age: 54, Gender: Female, Disease: Ahmedabad
ID: 130, Name: Neha Verma 130, Age: 42, Gender: Female, Disease: Kolkata
ID: 131, Name: Amit Khanna 131, Age: 58, Gender: Male, Disease: Kolkata
ID: 132, Name: Anjali Rao 132, Age: 32, Gender: Male, Disease: Ahmedabad
ID: 133, Name: Amit Khanna 133, Age: 23, Gender: Female, Disease: Mumbai
ID: 134, Name: Rahul Sharma 134, Age: 56, Gender: Male, Disease: Hyderabad
ID: 135, Name: Pooja Thakur 135, Age: 90, Gender: Male, Disease: Chennai
ID: 136, Name: Alok Singh 136, Age: 46, Gender: Female, Disease: Hyderabad
ID: 137, Name: Neha Verma 137, Age: 71, Gender: Male, Disease: Delhi
ID: 138, Name: Anjali Rao 138, Age: 89, Gender: Male, Disease: Jaipur
ID: 139, Name: Pooja Thakur 139, Age: 36, Gender: Female, Disease: Pune
ID: 140, Name: Amit Khanna 140, Age: 63, Gender: Female, Disease: Bangalore
ID: 141, Name: Suresh Patil 141, Age: 47, Gender: Female, Disease: Bangalore
ID: 142, Name: Suresh Patil 142, Age: 17, Gender: Male, Disease: Pune
ID: 143, Name: Deepika Reddy 143, Age: 7, Gender: Female, Disease: Hyderabad
ID: 144, Name: Amit Khanna 144, Age: 7, Gender: Female, Disease: Mumbai
ID: 145, Name: Priya Kapoor 145, Age: 74, Gender: Female, Disease: Kolkata
ID: 146, Name: Amit Khanna 146, Age: 60, Gender: Male, Disease: Delhi
ID: 147, Name: Priya Kapoor 147, Age: 2, Gender: Male, Disease: Jaipur
ID: 148, Name: Neha Verma 148, Age: 66, Gender: Female, Disease: Mumbai
ID: 149, Name: Suresh Patil 149, Age: 38, Gender: Female, Disease: Ahmedabad
ID: 150, Name: Pooja Thakur 150, Age: 14, Gender: Male, Disease: Delhi
ID: 151, Name: Suresh Patil 151, Age: 18, Gender: Female, Disease: Ahmedabad
ID: 152, Name: Priya Kapoor 152, Age: 80, Gender: Male, Disease: Bangalore
ID: 153, Name: Neha Verma 153, Age: 43, Gender: Female, Disease: Chennai
ID: 154, Name: Rahul Sharma 154, Age: 59, Gender: Female, Disease: Ahmedabad
ID: 155, Name: Amit Khanna 155, Age: 2, Gender: Male, Disease: Kolkata
ID: 156, Name: Rahul Sharma 156, Age: 56, Gender: Male, Disease: Chennai
ID: 157, Name: Vikas Mehta 157, Age: 39, Gender: Female, Disease: Kolkata
ID: 158, Name: Manish Gupta 158, Age: 17, Gender: Female, Disease: Ahmedabad
ID: 159, Name: Anjali Rao 159, Age: 32, Gender: Female, Disease: Bangalore
ID: 160, Name: Suresh Patil 160, Age: 50, Gender: Male, Disease: Ahmedabad
ID: 161, Name: Vikas Mehta 161, Age: 77, Gender: Female, Disease: Jaipur
ID: 162, Name: Priya Kapoor 162, Age: 40, Gender: Male, Disease: Delhi
ID: 163, Name: Pooja Thakur 163, Age: 76, Gender: Female, Disease: Kolkata
ID: 164, Name: Alok Singh 164, Age: 9, Gender: Female, Disease: Pune
ID: 165, Name: Manish Gupta 165, Age: 18, Gender: Female, Disease: Jaipur
ID: 166, Name: Alok Singh 166, Age: 9, Gender: Male, Disease: Mumbai
ID: 167, Name: Suresh Patil 167, Age: 3, Gender: Female, Disease: Pune
ID: 168, Name: Suresh Patil 168, Age: 33, Gender: Female, Disease: Bangalore
ID: 169, Name: Alok Singh 169, Age: 34, Gender: Male, Disease: Delhi
ID: 170, Name: Priya Kapoor 170, Age: 72, Gender: Male, Disease: Ahmedabad
ID: 171, Name: Priya Kapoor 171, Age: 29, Gender: Female, Disease: Bangalore
ID: 172, Name: Pooja Thakur 172, Age: 86, Gender: Female, Disease: Pune
ID: 173, Name: Deepika Reddy 173, Age: 13, Gender: Female, Disease: Jaipur
ID: 174, Name: Pooja Thakur 174, Age: 86, Gender: Female, Disease: Mumbai
ID: 175, Name: Vikas Mehta 175, Age: 20, Gender: Male, Disease: Kolkata
ID: 176, Name: Neha Verma 176, Age: 57, Gender: Male, Disease: Ahmedabad
ID: 177, Name: Deepika Reddy 177, Age: 72, Gender: Male, Disease: Bangalore
ID: 178, Name: Priya Kapoor 178, Age: 70, Gender: Female, Disease: Pune
ID: 179, Name: Manish Gupta 179, Age: 59, Gender: Male, Disease: Hyderabad
ID: 180, Name: Alok Singh 180, Age: 64, Gender: Male, Disease: Jaipur
ID: 181, Name: Suresh Patil 181, Age: 33, Gender: Male, Disease: Pune
ID: 182, Name: Deepika Reddy 182, Age: 75, Gender: Male, Disease: Hyderabad
ID: 183, Name: Rahul Sharma 183, Age: 34, Gender: Male, Disease: Jaipur
ID: 184, Name: Rahul Sharma 184, Age: 41, Gender: Male, Disease: Jaipur
ID: 185, Name: Pooja Thakur 185, Age: 7, Gender: Female, Disease: Ahmedabad
ID: 186, Name: Ramesh Iyer 186, Age: 40, Gender: Female, Disease: Chennai
ID: 187, Name: Deepika Reddy 187, Age: 79, Gender: Male, Disease: Chennai
ID: 188, Name: Vikas Mehta 188, Age: 75, Gender: Female, Disease: Mumbai
ID: 189, Name: Alok Singh 189, Age: 63, Gender: Female, Disease: Kolkata
ID: 190, Name: Anjali Rao 190, Age: 80, Gender: Male, Disease: Chennai
ID: 191, Name: Vikas Mehta 191, Age: 79, Gender: Female, Disease: Pune
ID: 192, Name: Ramesh Iyer 192, Age: 64, Gender: Male, Disease: Pune
ID: 193, Name: Amit Khanna 193, Age: 62, Gender: Male, Disease: Hyderabad
ID: 194, Name: Manish Gupta 194, Age: 67, Gender: Female, Disease: Chennai
ID: 195, Name: Ramesh Iyer 195, Age: 33, Gender: Male, Disease: Bangalore
ID: 196, Name: Alok Singh 196, Age: 63, Gender: Female, Disease: Pune
ID: 197, Name: Vikas Mehta 197, Age: 70, Gender: Male, Disease: Jaipur
ID: 198, Name: Deepika Reddy 198, Age: 46, Gender: Female, Disease: Ahmedabad
ID: 199, Name: Anjali Rao 199, Age: 32, Gender: Female, Disease: Hyderabad
ID: 200, Name: Manish Gupta 200, Age: 25, Gender: Male, Disease: Jaipur
ID: 201, Name: Alok Singh 201, Age: 17, Gender: Male, Disease: Chennai
ID: 202, Name: Ramesh Iyer 202, Age: 27, Gender: Female, Disease: Kolkata
ID: 203, Name: Neha Verma 203, Age: 54, Gender: Male, Disease: Ahmedabad
ID: 204, Name: Suresh Patil 204, Age: 54, Gender: Female, Disease: Chennai
ID: 205, Name: Ramesh Iyer 205, Age: 17, Gender: Female, Disease: Ahmedabad
ID: 206, Name: Suresh Patil 206, Age: 82, Gender: Female, Disease: Hyderabad
ID: 207, Name: Deepika Reddy 207, Age: 60, Gender: Female, Disease: Chennai
ID: 208, Name: Manish Gupta 208, Age: 37, Gender: Female, Disease: Chennai
ID: 209, Name: Suresh Patil 209, Age: 67, Gender: Female, Disease: Kolkata
ID: 210, Name: Suresh Patil 210, Age: 12, Gender: Female, Disease: Jaipur
ID: 211, Name: Rahul Sharma 211, Age: 37, Gender: Female, Disease: Chennai
ID: 212, Name: Anjali Rao 212, Age: 88, Gender: Female, Disease: Ahmedabad
ID: 213, Name: Suresh Patil 213, Age: 20, Gender: Female, Disease: Chennai
ID: 214, Name: Priya Kapoor 214, Age: 75, Gender: Female, Disease: Jaipur
ID: 215, Name: Vikas Mehta 215, Age: 89, Gender: Female, Disease: Chennai
ID: 216, Name: Priya Kapoor 216, Age: 2, Gender: Male, Disease: Hyderabad
ID: 217, Name: Pooja Thakur 217, Age: 81, Gender: Female, Disease: Hyderabad
ID: 218, Name: Amit Khanna 218, Age: 31, Gender: Male, Disease: Jaipur
ID: 219, Name: Anjali Rao 219, Age: 35, Gender: Female, Disease: Ahmedabad
ID: 220, Name: Deepika Reddy 220, Age: 82, Gender: Male, Disease: Mumbai
ID: 221, Name: Amit Khanna 221, Age: 53, Gender: Female, Disease: Delhi
ID: 222, Name: Suresh Patil 222, Age: 23, Gender: Male, Disease: Ahmedabad
ID: 223, Name: Manish Gupta 223, Age: 32, Gender: Male, Disease: Jaipur
ID: 224, Name: Neha Verma 224, Age: 46, Gender: Male, Disease: Chennai
ID: 225, Name: Anjali Rao 225, Age: 6, Gender: Female, Disease: Delhi
ID: 226, Name: Neha Verma 226, Age: 6, Gender: Female, Disease: Mumbai
ID: 227, Name: Manish Gupta 227, Age: 85, Gender: Male, Disease: Pune
ID: 228, Name: Pooja Thakur 228, Age: 54, Gender: Female, Disease: Ahmedabad
ID: 229, Name: Neha Verma 229, Age: 80, Gender: Female, Disease: Kolkata
ID: 230, Name: Neha Verma 230, Age: 42, Gender: Male, Disease: Hyderabad
ID: 231, Name: Pooja Thakur 231, Age: 9, Gender: Female, Disease: Hyderabad
ID: 232, Name: Priya Kapoor 232, Age: 8, Gender: Female, Disease: Delhi
ID: 233, Name: Anjali Rao 233, Age: 81, Gender: Male, Disease: Hyderabad
ID: 234, Name: Alok Singh 234, Age: 51, Gender: Female, Disease: Chennai
ID: 235, Name: Neha Verma 235, Age: 8, Gender: Male, Disease: Kolkata
ID: 236, Name: Suresh Patil 236, Age: 23, Gender: Female, Disease: Jaipur
ID: 237, Name: Ramesh Iyer 237, Age: 42, Gender: Male, Disease: Chennai
ID: 238, Name: Alok Singh 238, Age: 88, Gender: Female, Disease: Chennai
ID: 239, Name: Pooja Thakur 239, Age: 6, Gender: Male, Disease: Pune
ID: 240, Name: Deepika Reddy 240, Age: 10, Gender: Male, Disease: Ahmedabad
ID: 241, Name: Pooja Thakur 241, Age: 66, Gender: Female, Disease: Bangalore
ID: 242, Name: Suresh Patil 242, Age: 13, Gender: Male, Disease: Ahmedabad
ID: 243, Name: Alok Singh 243, Age: 52, Gender: Male, Disease: Hyderabad
ID: 244, Name: Amit Khanna 244, Age: 36, Gender: Female, Disease: Pune
ID: 245, Name: Vikas Mehta 245, Age: 61, Gender: Male, Disease: Pune
ID: 246, Name: Pooja Thakur 246, Age: 56, Gender: Female, Disease: Chennai
ID: 247, Name: Rahul Sharma 247, Age: 42, Gender: Male, Disease: Delhi
ID: 248, Name: Pooja Thakur 248, Age: 56, Gender: Male, Disease: Ahmedabad
ID: 249, Name: Anjali Rao 249, Age: 85, Gender: Male, Disease: Pune
ID: 250, Name: Anjali Rao 250, Age: 7, Gender: Male, Disease: Jaipur
ID: 251, Name: Ramesh Iyer 251, Age: 62, Gender: Female, Disease: Pune
ID: 252, Name: Amit Khanna 252, Age: 75, Gender: Male, Disease: Kolkata
ID: 253, Name: Deepika Reddy 253, Age: 63, Gender: Male, Disease: Hyderabad
ID: 254, Name: Deepika Reddy 254, Age: 73, Gender: Female, Disease: Jaipur
ID: 255, Name: Vikas Mehta 255, Age: 8, Gender: Male, Disease: Chennai
ID: 256, Name: Rahul Sharma 256, Age: 76, Gender: Male, Disease: Ahmedabad
ID: 257, Name: Ramesh Iyer 257, Age: 11, Gender: Female, Disease: Mumbai
ID: 258, Name: Suresh Patil 258, Age: 53, Gender: Female, Disease: Bangalore
ID: 259, Name: Alok Singh 259, Age: 43, Gender: Female, Disease: Jaipur
ID: 260, Name: Anjali Rao 260, Age: 35, Gender: Female, Disease: Ahmedabad
ID: 261, Name: Rahul Sharma 261, Age: 35, Gender: Female, Disease: Bangalore
ID: 262, Name: Deepika Reddy 262, Age: 70, Gender: Female, Disease: Ahmedabad
ID: 263, Name: Anjali Rao 263, Age: 35, Gender: Male, Disease: Pune
ID: 264, Name: Alok Singh 264, Age: 64, Gender: Male, Disease: Hyderabad
ID: 265, Name: Alok Singh 265, Age: 25, Gender: Male, Disease: Hyderabad
ID: 266, Name: Neha Verma 266, Age: 32, Gender: Female, Disease: Delhi
ID: 267, Name: Suresh Patil 267, Age: 22, Gender: Male, Disease: Delhi
ID: 268, Name: Rahul Sharma 268, Age: 2, Gender: Female, Disease: Bangalore
ID: 269, Name: Rahul Sharma 269, Age: 66, Gender: Female, Disease: Hyderabad
ID: 270, Name: Neha Verma 270, Age: 59, Gender: Female, Disease: Mumbai
ID: 271, Name: Deepika Reddy 271, Age: 47, Gender: Female, Disease: Delhi
ID: 272, Name: Alok Singh 272, Age: 25, Gender: Male, Disease: Bangalore
ID: 273, Name: Ramesh Iyer 273, Age: 29, Gender: Female, Disease: Mumbai
ID: 274, Name: Vikas Mehta 274, Age: 52, Gender: Female, Disease: Mumbai
ID: 275, Name: Alok Singh 275, Age: 62, Gender: Male, Disease: Mumbai

### Making Patients Data as a Dataframe :

In [157]:
import pandas as pd
import sqlalchemy
engine = sqlalchemy.create_engine(f"mysql+pymysql://{"root"}:{"mysql"}@{"localhost"}/{"hospital_management_system"}")

In [256]:
df = pd.read_sql("select * from Patients",engine, index_col=["patient_id"])

In [258]:
df

,patient_name,age,gender,address,contact_number,medical_history
patient_id,,,,,,
2,Ramesh Iyer 2,52,Male,Jaipur,9899653422,None
3,Deepika Reddy 3,82,Female,Hyderabad,9307924191,Asthma
4,Priya Kapoor 4,77,Male,Chennai,9748276329,Corona
5,Rahul Sharma 5,37,Male,Jaipur,9240114653,Asthma
6,Pooja Thakur 6,77,Female,Pune,9148271369,Heart Disease
...,...,...,...,...,...,...
498,Rahul Sharma 498,62,Male,Pune,9149992494,Diabetes
499,Pooja Thakur 499,53,Male,Ahmedabad,9594106336,None
500,Amit Khanna 500,50,Female,Delhi,9704275822,Diabetes
501,Roxx,28,Male,Mumbai,9375672652,Anxiety disorder
503,Roxxx,28,Male,Mumbai,9373472652,Anxiety disorder

## DML Command Operations :

### Inserting New patients :

In [205]:
def insert_patient(patient_name, age, gender, address,	contact_number,	medical_history):
    query = "INSERT INTO patients (patient_name, age, gender, address,	contact_number,	medical_history) VALUES (%s, %s, %s, %s, %s, %s)"
    values = (patient_name, age, gender, address,	contact_number,	medical_history)
    cursor.execute(query, values)
    conn.commit()
    print("Patient added successfully!")

In [254]:
insert_patient("Roxxx",28, "Male", "Mumbai",  9373472652, "Anxiety disorder")

Patient added successfully!

### Updating Medical_History :

In [195]:
def update_patient(patient_id, new_disease):
    query = "UPDATE patients SET medical_history = %s WHERE patient_id = %s"
    values = (new_disease, patient_id)
    cursor.execute(query, values)
    conn.commit()
    print(f"Patient ID {patient_id} updated successfully!")

In [197]:
update_patient(4,"Corona")

Patient ID 4 updated successfully!

### Deleting Patient Details :

In [240]:
def delete_patient(patient_id):
    query = "DELETE FROM patients WHERE patient_id = %s"
    values = (patient_id,)
    cursor.execute(query, values)
    conn.commit()
    print(f"Patient ID {patient_id} deleted successfully!")

In [242]:
delete_patient(1)

Patient ID 1 deleted successfully!